pipeline {

    agent {
        docker {
            image 'node:12-alpine'
        }
    }

    environment {
        HOME = '.'
    }

    stages {
        stage('Cucumber Test') {
            steps {
                sh 'npm install'
                sh 'npm run test'
                publishHTML(
                    [
                        allowMissing: false, 
                        alwaysLinkToLastBuild: false, 
                        keepAll: false, reportDir: 'test/report/', 
                        reportFiles: 'cucumber_report.html', 
                        reportName: 'cucumber_report.html', 
                        reportTitles: ''
                    ]
                )
            }
        }
         stage('Import xray results') {
            steps {
                    step(
                    [
                        $class: 'XrayImportBuilder', 
                        endpointName: '/cucumber/multipart', 
                        importFilePath: 'test/report/cucumber_report.json', 
                        importInfo: '''{
                            "fields": {
                                "project": {
                                    "key": "CALC"
                                },
                                "summary": "Test Execution for Cucumber results (Generated by job: ${BUILD_TAG})",
                                "issuetype": {
                                    "id": "10008"
                                }
                            }
                            }''', 
                        inputInfoSwitcher: 'fileContent', 
                        serverInstance: 'CLOUD-cb430a15-4fa5-4c52-bec2-7606bd1e7357'
                    ]
                )
            }
        }

    }


    post{
        failure{
            step(
                [
                    $class: 'XrayImportBuilder', 
                    endpointName: '/cucumber/multipart', 
                    importFilePath: 'test/report/cucumber_report.json', 
                    importInfo: '''{
                        "fields": {
                            "project": {
                                "key": "CALC"
                            },
                            "summary": "Test Execution for Cucumber results (Generated by job: ${BUILD_TAG})",
                            "issuetype": {
                                "id": "10008"
                            }
                        }
                        }''', 
                    inputInfoSwitcher: 'fileContent', 
                    serverInstance: 'CLOUD-cb430a15-4fa5-4c52-bec2-7606bd1e7357'
                ]
            )
        }
    }          
}